message = """OWSUK TOYUV VRAYS JVSXP GSLYX LBVVQ OIOWD MSPBV FSPPQ TZQIP GNZET PGLRG VCWUS
CGFQQ LNJPD NRGYT FCICJ TUGIA KESPF LIPSV ACYAS TVOAP JQLQK YOWIC FLIVR LZLRG
TFOQT TVPKE QJZDL CSTCC YOWHW CXPBV JKKDG CXCYU SULGY GFCZK KYHHZ CXOSX FSYUO
LFSZP GKDNR PAGER WFSNH SKDZK XLKDD QLPGW ZQEEK CZGKC DESOR GYUSV ZCTDO NVPKA
SVVPP PGWZQ BCOKD CTETK VPJPJ QLQPP ZGJMA WWIEC GYCWM CGFDQ LPWFS OFLSP GUREK
DCKKZ OPBEC YOCCW ZHKDI KJDOP FFVTU FG"""

def propre(msg):
    msg = msg.replace(" ", "")
    return msg

print(propre(message))